name: Bevinding iWlz (v2)
description: Issue voor het opvoeren van een bevinding
title: "[Onderwerp bevinding]"
labels: ["iWlz", "Bevinding"]
projects: ["iStandaarden/9"]
type: "Bevinding"
body:
- type: input
  id: topdesk
  attributes: 
    label: Topdesknr 
    placeholder: Topdesknummer
  validations:
    required: false
- type: textarea
  id: probleem
  attributes:
    label: Probleem beschrijving
    placeholder: | 
      Geef een omschrijving van de bevinding, waarin het probleem, de situatie, of afwijking wordt beschreven.
      Geef bijvoorbeeld een lijst van duidelijke, stapsgewijze instructies om het probleem opnieuw te kunnen zien en specifieke gegevens of inputs die nodig zijn om het probleem te reproduceren.
  validations:
    required: true
- type: textarea
  id: wijziging
  attributes:
    label: Omschrijving verwachte resultaat
    placeholder: | 
      Beschrijf het verwachte resultaat of geef eventueel een suggestie of idee om het probleem op te lossen (indien bekend).
  validations:
    required: true
- type: dropdown
  id: impact_onderdelen
  attributes:
    label: Op welk onderdeel / welke onderdelen heeft de bevinding betrekking?
    multiple: true
    options:
      - Codelijsten
      - Documentatie / Afsprakenstelsel
      - ERD (Register)
      - Koppelvlak specificatie
      - Regels
      - XSD 
      - anders, (geef hieronder aan)
  validations:
    required: true
- type: input
  id: ander_onderdeel
  attributes:
    label: Welk ander onderdeel?
    description: Op welk ander onderdeel heeft de bevinding gevolgen
- type: dropdown
  id: impact_partij
  attributes:
    label: Betrokken partij RFC
    multiple: true
    options:
      - CAK
      - CIZ
      - Zorgaanbieder
      - Zorgkantoor
      - Zorginstituut
      - anders, (geef aan bij andere partij)
  validations:
    required: true
- type: input
  id: andere_partij
  attributes:
    label: Andere betrokken partij 
    placeholder: Naam andere partij
- type: dropdown
  id: indiener
  attributes:
    label: Indiener bevinding
    multiple: true
    options:
      - CAK
      - CIZ
      - Softwareleverancier zorgaanbieder
      - Softwareleverancier zorgkantoor
      - Zorgaanbieder
      - Zorgkantoor
      - Zorginstituut
      - anders, (geef aan bij contactpersoon)
  validations:
    required: true
- type: input
  id: contactpersoon
  attributes:
    label: Andere organisatie / contactpersoon
    placeholder: Naam andere organisatie / contactpersoon
- type: markdown
  attributes:
    value: <hr>
- type: markdown
  attributes:
    value: "## Conclusie en Oplossing"
- type: textarea
  id: oplossing
  attributes:
    label: Oplossing
    placeholder: Ruimte voor beschrijving oplossing
- type: dropdown
  id: conclusie
  attributes:
    label: Conclusie
    options:
      - Doorvoeren oplossing
      - Verwerpen (bevinding niet gegrond)


