name: Taak iWlz (v1)
description: Issue voor het opvoeren van een taak t.b.v. Implementatie
title: "[Onderwerp Taak]"
labels: ["Nieuw"]
projects: ["iStandaarden/9" ]
type: "Taak"
body:
- type: textarea
  id: taak
  attributes:
    label: Taak beschrijving
    placeholder: | 
      Geef een omschrijving van de taak.
  validations:
    required: true

