name: Bevinding iWlz
description: Issue voor het opvoeren van een bevinding
title: "[onderwerp]"
labels: ["iWlz", "bevinding"]
projects: ["iStandaarden/9"]
body:
- type: input
  id: topdesk
  attributes: 
    label: Topdesknr 
    placeholder: Topdesknummer
  validations:
    required: false
- type: markdown
  attributes:
    value: <hr>
- type: markdown
  attributes:
    value: "# Onderwerp Bevinding"
- type: textarea
  id: probleem
  attributes:
    label: Probleem omschrijving
    placeholder: Geef omschrijving van het probleem
  validations:
    required: true
- type: textarea
  id: wijziging
  attributes:
    label: Omschrijving verwachte resultaat
    placeholder: Beschrijf het verwachte resultaat
  validations:
    required: true
- type: dropdown
  id: impact_onderdelen
  attributes:
    label: RFC gevolgen voor het onderdeel/de onderdelen
    multiple: true
    options:
      - Codelijsten
      - Documentatie / Afsprakenstelsel
      - ERD (Register)
      - Koppelvlak specificatie
      - Regels
      - XSD 
      - anders, (geef hieronder aan)
  validations:
    required: true
- type: input
  id: ander_onderdeel
  attributes:
    label: Welk ander onderdeel?
    description: Voor welk ander onderdeel heeft de RFC gevolgen
- type: dropdown
  id: impact_partij
  attributes:
    label: Betrokken partij RFC
    multiple: true
    options:
      - CAK
      - CIZ
      - Zorgaanbieder
      - Zorgkantoor
      - Zorginstituut
      - anders, (geef aan bij contactpersoon)
  validations:
    required: true
- type: input
  id: andere_partij
  attributes:
    label: Andere betrokken partij 
    placeholder: Naam andere partij
- type: markdown
  attributes:
    value: |
      <hr>
- type: markdown
  attributes: 
    value: "# Contactgegevens indiener"
- type: dropdown
  id: indiener
  attributes:
    label: Indiener RFC
    options:
      -
      - CAK
      - CIZ
      - Softwareleverancier zorgaanbieder
      - Softwareleverancier zorgkantoor
      - Zorgaanbieder
      - Zorgkantoor
      - Zorginstituut
      - anders, (geef aan bij contactpersoon)
  validations:
    required: true
- type: input
  id: contactpersoon
  attributes:
    label: Andere organisatie / contactpersoon
    placeholder: Naam andere organisatie / contactpersoon
- type: markdown
  attributes:
    value: <hr>
- type: markdown
  attributes:
    value: "# Conclusie en Oplossing"
- type: textarea
  id: oplossing
  attributes:
    label: Oplossing
    placeholder: Ruimte voor beschrijving oplossing
- type: dropdown
  id: conclusie
  attributes:
    label: Conclusie
    options:
      - Doorvoeren oplossing
      - Verwerpen (bevinding niet gegrond)
- type: input
  id: implementatie
  attributes:
    label: Implementatiemoment / Ingang gekozen oplossing
    placeholder: "[yyyy-mm-dd]/zo snel mogelijk/nvt"
- type: input
  id: publicatie
  attributes:
    label: Publicatiemoment
    placeholder: "[yyyy-mm-dd]/zo snel mogelijk/nvt"


