blank_issues_enabled: false
contact_links:
  - name: Overzicht ingediende Wijzigingsverzoeken
    url: https://github.com/orgs/iStandaarden/projects/9/views/5
    about: Bekijk welke wijzigingsverzoeken zijn ingediend en wat de status is.
  - name: Overzicht Bevindingen
    url: https://github.com/orgs/iStandaarden/projects/9/views/12
    about: Bekijk welke bevindingen er zijn. 
  - name: Afgesloten wijzigingsverzoeken en bevindingen
    url: https://github.com/orgs/iStandaarden/projects/9/views/11
    about: Afgesloten wijzigingsverzoeken en bevindingen
  - name: Meer informatie over het proces wijzigingsverzoeken en bevindingen
    url: https://github.com/iStandaarden/iWlz_RequestForChange/wiki
    about: Ga naar de wiki en lees meer over het proces van afhandelen wijzigingsverzoeken en bevindingen, wat is het verschil, wat is een release etc. 
