name: Wijzigingsverzoek
description: Issue voor het volgen van een Wijzigingsverzoek
title: "[RFC-#### - [onderwerp]]"
labels: ["iWlz"]
projects: ["iStandaarden/9"]
body:
- type: input
  id: eDocsnr
  attributes: 
    label: eDocs volgnummer
    placeholder: eDocs volgnummer
  validations:
    required: false
- type: input
  id: versie
  attributes:
    label: Versienummer RFC
    placeholder: Versienummer RFC
  validations:
    required: true
- type: markdown
  attributes:
    value: "# Onderwerp wijzigingsverzoek"
- type: textarea
  id: samenvatting
  attributes:
    label: Korte probleem omschrijving
    placeholder: Geef een korte omschrijving van het probleem
  validations:
    required: true
- type: textarea
  id: wijziging
  attributes:
    label: Korte omschrijving voorgestelde oplossing
    placeholder: Beschrijf de voorgestelde oplossing(srichting) of het gewenste resultaat
  validations:
    required: true
- type: checkboxes
  id: impact_onderdelen
  attributes:
    label: RFC gevolgen voor
    options:
      - label: Codelijsten
      - label: Documentatie
      - label: Regels
      - label: XSD
      - label: ERD
      - label: Koppelvlak specificatie 
      - label: anders, (geef hieronder aan)
        required: true
- type: textarea
  id: anders
  attributes:
    label: Welk ander onderdeel?
    description: Voor welk ander onderdeel heeft de RFC gevolgen
- type: checkboxes
  id: impact_partij
  attributes:
    label: Betrokken partij RFC
    options:
      - label: CAK
      - label: CIZ
      - label: Zorgaanbieder
      - label: Zorgkantoor
      - label: Zorginstituut
      - label: anders, (geef aan bij contactpersoon)
        required: true
- type: input
  id: andere_partij
  attributes:
    label: Andere partij 
    placeholder: Naam andere partij
- type: markdown
  attributes: 
    value: "# Contactgegevens indiener"
- type: dropdown
  id: indiener
  attributes:
    label: Indiener RFC
    options:
      - CAK
      - CIZ
      - Softwareleverancier Zorgaanbieder
      - Softwareleverancier Zorgkantoor
      - Zorgaanbieder
      - Zorgkantoor
      - Zorginstituut
      - anders, (geef aan bij contactpersoon)
  validations:
    required: true
- type: input
  id: contactpersoon
  attributes:
    label: Andere organisatie / contactpersoon
    placeholder: Naam andere organisatie / contactpersoon
- type: markdown
  attributes:
    value: <hr>
- type: checkboxes
    id: project_values
    attributes:
      label: controleer project en labels van het issue
      description: onder 'Projects', klik op het 'tandwieltje'
      options:
        - label: gecontroleerd
          required: true

