name: Wijzigingsverzoek iWlz + analyse
description: Issue voor het volgen van een Wijzigingsverzoek
title: "[RFC-#### - onderwerp]"
labels: ["iWlz"]
projects: ["iStandaarden/9"]
body:
- type: input
  id: eDocsnr
  attributes: 
    label: eDocs volgnummer
    placeholder: eDocs volgnummer
  validations:
    required: false
- type: input
  id: versie
  attributes:
    label: Versienummer RFC
    placeholder: Versienummer RFC
  validations:
    required: true
- type: markdown
  attributes:
    value: "# Onderwerp wijzigingsverzoek"
- type: textarea
  id: samenvatting
  attributes:
    label: Korte probleem omschrijving
    placeholder: Geef een korte omschrijving van het probleem
  validations:
    required: true
- type: textarea
  id: wijziging
  attributes:
    label: Korte omschrijving voorgestelde oplossing
    placeholder: Beschrijf de voorgestelde oplossing(srichting) of het gewenste resultaat
  validations:
    required: true
- type: dropdown
  id: impact_onderdelen
  attributes:
    label: RFC gevolgen voor het onderdeel/de onderdelen
    multiple: true
    options:
      - Codelijsten
      - Documentatie / Afsprakenstelsel
      - ERD (Register)
      - Koppelvlak specificatie
      - Regels
      - XSD 
      - anders, (geef hieronder aan)
  validations:
    required: true
- type: input
  id: ander_onderdeel
  attributes:
    label: Welk ander onderdeel?
    description: Voor welk ander onderdeel heeft de RFC gevolgen
- type: dropdown
  id: impact_partij
  attributes:
    label: Betrokken partij RFC
    multiple: true
    options:
      - CAK
      - CIZ
      - Zorgaanbieder
      - Zorgkantoor
      - Zorginstituut
      - anders, (geef aan bij contactpersoon)
  validations:
    required: true
- type: input
  id: andere_partij
  attributes:
    label: Andere partij 
    placeholder: Naam andere partij
- type: markdown
  attributes: 
    value: "# Contactgegevens indiener"
- type: dropdown
  id: indiener
  attributes:
    label: Indiener RFC
    options:
      -
      - CAK
      - CIZ
      - Softwareleverancier zorgaanbieder
      - Softwareleverancier zorgkantoor
      - Zorgaanbieder
      - Zorgkantoor
      - Zorginstituut
      - anders, (geef aan bij contactpersoon)
  validations:
    required: true
- type: input
  id: contactpersoon
  attributes:
    label: Andere organisatie / contactpersoon
    placeholder: Naam andere organisatie / contactpersoon
- type: markdown
  attributes:
    value: "# Onderdelen analyse"
- type: textarea
  id: analyse
  attributes:
    label: Analyse
    placeholder: Ruimte voor analyse
- type: textarea
  id: oplossing
  attributes:
    label: Oplossing
    value: |
      | Oplossing     | Voordeel / Nadeel                | Overweging Referentiegroep |
      | :------------ | :------------------------------- | :------------------------- |
      | 1. ..         | Voordeel:                        |                            |
      |               | Nadeel:                          |                            |
      | #. Niets doen | Voordeel: geen wijziging nodig   |                            |
      |               | Nadeel: probleem blijft aanwezig |                            |
      ...
- type: markdown
  attributes:
    value: <hr>
- type: checkboxes
  id: project_values
  attributes:
    label: controleer project en labels van het issue
    options:
      - label: gecontroleerd
        required: true
