name: Wijzigingsverzoek iWlz (v2)
description: Issuetype voor indienen van een iWlz Wijzigingsverzoek. (v2)
title: "Onderwerp van het wijzigingsverzoek"
labels: ["iWlz", "Verbetering", "Nieuw"]
projects: ["iStandaarden/9"]
type: "Wijzigingsverzoek"
body:
- type: textarea
  id: wijziging-omschrijving
  attributes:
    label: Beschrijving van de wijziging
    placeholder: Beschrijving van de verandering. Waarom is de wijziging nodig? Wat is het probleem of de situatie die moet worden opgelost?
  validations:
    required: true
- type: textarea
  id: wijziging
  attributes:
    label: Beoogde resultaat
    placeholder: | 
     Wat moet de wijziging bereiken? Wat zijn de voordelen van de verandering? Bijvoorbeeld verbeterde efficiëntie, lagere kosten of betere beveiliging.
     [voeg eventueel aanvullende documentatie toe]
  validations:
    required: true
- type: textarea
  id: risico
  attributes:
    label: Risico's
    placeholder: | 
     Mogelijke problemen die kunnen optreden als gevolg van de wijziging. Zijn er op voorhand risico's bekend?
  validations:
    required: false
- type: dropdown
  id: impact_onderdelen
  attributes:
    label: Op welk onderdeel / welke onderdelen heeft de wijziging betrekking
    description: Selecteer de onderdelen waarop de wijziging betrekking heeft.
    multiple: true
    options:
      - Codelijsten
      - Documentatie / Afsprakenstelsel
      - ERD (Register)
      - XSD 
      - Koppelvlak specificatie
      - Regels
      - Autorisatie (policy/query/matrix)
      - anders, (geef hieronder aan)
  validations:
    required: true
- type: input
  id: ander_onderdeel
  attributes:
    label: Welk ander onderdeel?
    description: Voor welk ander onderdeel heeft het wijzigingsverzoek gevolgen
- type: dropdown
  id: impact_partij
  attributes:
    label: Betrokken partij RFC
    multiple: true
    options:
      - CAK
      - CIZ
      - Zorgaanbieder
      - Zorgkantoor
      - Zorginstituut
      - anders, (geef aan ander betrokken partij)
  validations:
    required: true
- type: input
  id: andere_partij
  attributes:
    label: Andere betrokken partij 
    placeholder: Naam andere partij
- type: dropdown
  id: indiener
  attributes:
    label: Indiener RFC
    multiple: true
    options:
      - CAK
      - CIZ
      - Softwareleverancier zorgaanbieder
      - Softwareleverancier zorgkantoor
      - Zorgaanbieder
      - Zorgkantoor
      - Zorginstituut
      - anders, (geef aan bij contactpersoon)
  validations:
    required: true
- type: input
  id: contactpersoon
  attributes:
    label: Andere organisatie / contactpersoon
    placeholder: Naam andere organisatie / contactpersoon
- type: dropdown
  id: urgentie
  attributes:
    label: Gewenste implementatiemoment
    multiple: false
    options:
      - nader te bepalen
      - eerst volgende gelegendheid
  validations:
    required: true
