name: Wijzigingsverzoek iWlz + analyse versie 2
description: Issuetype voor indienen van een iWlz Wijzigingsverzoek
title: "RFC #### - onderwerp"
labels: ["iWlz", "Verbetering"]
projects: ["iStandaarden/9"]
body:
- type: input
  id: eDocsnr
  attributes: 
    label: eDocs volgnummer
    placeholder: eDocs volgnummer
  validations:
    required: false
- type: markdown
  attributes:
    value: <hr>
- type: textarea
  id: samenvatting
  attributes:
    label: Korte probleem omschrijving
    placeholder: Geef een korte omschrijving van het probleem
  validations:
    required: true
- type: textarea
  id: wijziging
  attributes:
    label: Korte omschrijving voorgestelde oplossing
    placeholder: Beschrijf de voorgestelde oplossing(srichting) of het gewenste resultaat
  validations:
    required: true
- type: dropdown
  id: impact_onderdelen
  attributes:
    label: RFC gevolgen voor het onderdeel/de onderdelen
    multiple: true
    options:
      - Codelijsten
      - Documentatie / Afsprakenstelsel
      - ERD (Register)
      - Koppelvlak specificatie
      - Regels
      - XSD 
      - Autorisatie (policy/query)
      - anders, (geef hieronder aan)
  validations:
    required: true
- type: input
  id: ander_onderdeel
  attributes:
    label: Welk ander onderdeel?
    description: Voor welk ander onderdeel heeft de RFC gevolgen
- type: dropdown
  id: impact_partij
  attributes:
    label: Betrokken partij RFC
    multiple: true
    options:
      - CAK
      - CIZ
      - Zorgaanbieder
      - Zorgkantoor
      - Zorginstituut
      - anders, (geef aan bij contactpersoon)
  validations:
    required: true
- type: input
  id: andere_partij
  attributes:
    label: Andere betrokken partij 
    placeholder: Naam andere partij
- type: markdown
  attributes:
    value: |
      <hr>
- type: dropdown
  id: indiener
  attributes:
    label: Indiener RFC
    multiple: true
    options:
      - CAK
      - CIZ
      - Softwareleverancier zorgaanbieder
      - Softwareleverancier zorgkantoor
      - Zorgaanbieder
      - Zorgkantoor
      - Zorginstituut
      - anders, (geef aan bij contactpersoon)
  validations:
    required: true
- type: input
  id: contactpersoon
  attributes:
    label: Andere organisatie / contactpersoon
    placeholder: Naam andere organisatie / contactpersoon
- type: markdown
  attributes:
    value: |
      <hr>
- type: textarea
  id: analyse
  attributes:
    label: Analyse
    value: |
      ---
      ### Huidige situatie
      <beschrijving huidige situatie>

      ### Bezwaren huidige situatie
      <beschrijving bezwaren situatie>

      ### Voorstel aanpassing
      <voorstel wijziging>

      **Voordelen**
      <voordelen>

      **Nadelen**
      <nadelen>

      ### Beknopte beschrijving wijziging per onderdeel
      #### ERD

      #### Regels

      #### Proces

      #### Gegevens

      #### Koppelvlak

      #### Policy en query-template
- type: textarea
  id: overweging
  attributes:
    label: Overweging
    value: |
      # Overweging wijzigingsvoorstel(len)
      
      | Oplossing     | Voordeel / Nadeel                | Overweging                 |
      | :------------ | :------------------------------- | :------------------------- |
      | 1. ..         | Voordeel:                        |                            |
      |               | Nadeel:                          |                            |
      | #. Niets doen | Voordeel: geen wijziging nodig   |                            |
      |               | Nadeel: probleem blijft aanwezig |                            |
      ...
- type: markdown
  attributes:
    value: |
      <hr>
- type: markdown
  attributes:
    value: "# Conclusie en Planning"
- type: dropdown
  id: conclusie
  attributes:
    label: Conclusie
    options:
      - Doorvoeren oplossing
      - Verwerpen (keuze Niets doen)
- type: input
  id: gekozenoplossing
  attributes:
    label: Gekozen oplossing
- type: input
  id: publicatie
  attributes:
    label: Publicatiemoment
    placeholder: "[yyyy-mm-dd]/zo snel mogelijk/nvt"
- type: input
  id: implementatie
  attributes:
    label: Implementatiemoment
    placeholder: "[yyyy-mm-dd]/zo snel mogelijk/nvt"
- type: markdown
  attributes:
    value: <hr>
- type: markdown
  attributes:
    value: |
      <hr>
