name: Request For Comments
description: Issue voor het volgen van een Request for Comments
title: "[neem de titel RFC hier over]"
labels: ["netwerk"]
body:
  - type: input
    id: link
    attributes:
      label: Link naar RFC
      placeholder: "plak hier de volledige link naar het RFC document, bijvoorbeeld: https://github.com/iStandaarden/iWlz-RFC/blob/main/RFC%20-%20Template.md"
    validations:
      required: true
  - type: textarea
    id: onderwerp
    attributes:
      label: Onderwerp
      placeholder: Geef hier een korte omschrijving van het onderwerp van de RFC
    validations:
      required: true
  - type: checkboxes
    id: impact_onderdelen
    attributes:
      label: RFC heeft impact op
      options:
        - label: Indicatieregister
        - label: Bemiddelingsregister - Centraal
        - label: Bemiddelingsregister - Decentraal
        - label: CIZ back-office
        - label: CIZ Netwerkadapter
        - label: nID 
        - label: Silvester
        - label: Raadplegers / GraphQL
        - label: anders, (geef hieronder aan)
  - type: textarea
    id: anders
    attributes:
      label: Welk ander onderdeel?
      description: voor welk ander onderdeel is de impact behoordeeld
  - type: checkboxes
    id: project
    attributes:
      label: Selecteer in de kolom rechts het project "RFC-netwerkmodel"
      description: onder 'Projects', klik op het 'tandwieltje'
      options:
        - label: done
          required: true
